version: '3.8'

services:
  service-mariadb:
    container_name: mariadb-10.9.3
    image: mariadb:10.9.3
    restart: always
    environment:
       - MARIADB_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
       - MARIADB_DATABASE=${DATABASE_NAME}
       - MARIADB_USER=${DATABASE_USER}
       - MARIADB_PASSWORD=${DATABASE_PASSWORD}
    ports:
        - 3306:3306
    volumes:
      - database:/var/lib/mariadb/data

  service-php-fpm:
    container_name: php-8.1.10-fpm
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./php-fpm
      args:
        HOST_USERNAME: ${DOCKER_HOST_USERNAME}
        HOST_UID: ${DOCKER_HOST_UID}
        HOST_GID: ${DOCKER_HOST_GID}
    hostname: php-8.1.10-fpm
    depends_on:
      - service-mariadb
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./../symfony/:/var/www
    user: ${DOCKER_HOST_UID}:${DOCKER_HOST_GID}

  service-nginx:
    container_name: nginx-1.23.1
    build:
      context: ./nginx
    volumes:
      - ./../symfony/:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/tmp/log
    depends_on:
      - service-php-fpm
    ports:
      - "80:80"
      - "443:443"

volumes:
  database:
    driver: local
